language: java
before_script:
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get install libavformat-dev
  - sudo apt-get install ffmpeg
  - sudo apt-get install libcv2.1
  - sudo apt-get install libcvaux2.1
  - sudo apt-get install libhighgui2.1
  - sudo apt-get install libcv-dev
  - sudo apt-get install libcvaux-dev
  - sudo apt-get install libhighgui-dev
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export MAVEN_OPTS=-Dsikuli-script=target/sikuli-script.jar
script: 
  - mvn test


